# Generated by Django 5.1.7 on 2025-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0011_alter_review_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-02 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poems_images/'),
        ),
        migrations.AddField(
            model_name='poem',
            name='title',
            field=models.CharField(default='Без назви', max_length=255),
        ),
    ]
